spring:
  application:
    name: rest-service-end

  zipkin:
#    baseUrl: http://zipkin:9411/
    baseUrl: http://rest-service-collector:9412/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 16000