server:
  port: 18898

spring:
  application:
    name: api-server

#//jichao
#myConfig:
#  apiServer: https://10.141.212.21:6443
#  token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi12cWxrcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY4NjE1ZTJkLTNhM2ItMTFlOC04NzIxLTAwNTA1NmE0NjY0MCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.IHTUz_oNuGoeEzKgwXrZTiyT5yCihAUcxOn9SwS_UwyHH54eToWcEOpAEt8r74LGW-r5nf_DL8YJuGe-NVqDYhEvmZNAJ9wU-lBYQgyiKDUkcLI_IeIO7AnaBM14Ip-D8O7CC3kSW1haP_bo6MDmN6r5mNq4ExXQiBYkPje-2mJPDS9EaW4xRBzFQUQDfWZmPW5Ujljri_MDmj5H1seRfIreAH4MwEMg61mTFfj1qBRFFGNUptY9rnSd6jmBZom-MTcz24FnD93sT2WgS28eMLGjyuuoAH8a7jHex2i-dvWBO_tzYq2z_NRFEFD1gRkUNENRWx29Vc0DeyXztiQS7g

#// hechuan
myConfig:
  clusters:
#    -
#      name: cluster1
#      masterIp: 10.141.212.23
#      username: root
#      passwd: root
#      apiServer: https://10.141.212.23:6443
#      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1zbjhqbCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjE0MGI3ZTEwLTkxNDYtMTFlOC1iYjY3LTAwNTA1NmE0MjQyYSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.WaTBjj_wY0BEwfzN6K0DJrhkWppMTp41sbR18ZklKZBm3uQ3gkU4E87K08LF5_qenEshfaZz7RB7gy8x8hYBX19QcYhfeu_YaFrSOga6v3xi_oMDhA7tU0-thgo0sNYCLnP5uns3nt1bMSnjvUg-SW1EDUbx7YwlAdFiwBYNX_pjJ9nQYFg0ruCOfw7VR8wHkyBjAhGsBCL_2ba7neP5tPyLkKwFuXYIONeZ_bSIMS_a6zQzra6vKqCAsRXG5ZFKsJ-r6lcikx0YcSgSeVR8dPdOAsvcyiluDknn4I7VxkdcBhIcYMF7LLY7fgRuK44oASpa3Rj6LZrEX9PELtpYCw

    -
      name: cluster2
      masterIp: 10.141.211.179
      username: root
      passwd: root
      apiServer: https://10.141.211.179:6443
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1jY3o2cSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhjODhlYmFkLWEwNjYtMTFlOC1iOWFhLTAwNTA1NmE0YjQ0MiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.hefaC-NOlS7hDeuG6vSCN0VkAKIuydmvLCCwK--wL6O1uFU27l6vfLAdOAMHOJMuCCDEbRU5udbmbUgIMqtqyIyjM4Ss5S504DNNW9AVsfgrjB9mOdygMos3yHZ2zqnK5PyER3jWY4iiIZ-u53zOcprHu4ve2xGFtwUIa0jr040403XpVnpgioSxhLP8XD5QTbdU9V-vnFom8Lj5XEglLRBKtXkV7ZlCQDp87AMc0MwqHNurE1EWGJ10Xq3GsxdA-yISm89RPPeLVrIbohxYJhjWdAKjZVrh14ZoObmPhwU4KDth9LD3fi9wH0AQlU5dhuJa_Oda7de2jHE_V_zNyg
