version: '3'
services:

  rest-service-y:
    build: rest-service-python
    image: my-service-cluster/rest-service-python
    # image: 10.141.212.25:5555/rest-service-python
    restart: always
    ports:
      - 16101:16101
    networks:
      - my-network


networks:
  my-network:
    # driver: overlay
    driver: bridge





  
