version: '3'
services:
  kafka:
    container_name: kafka
    image: spotify/kafka:latest
    ports:
     - 16005:2181
     - 16006:9092
    networks:
      - my-network
networks:
  my-network:
    # driver: overlay
    driver: bridge