spring:
  application:
    name: rest-service-collect

  rabbitmq:
    host: rabbitmq
    listener:
      retry:
        enabled: false
        max-attempts: 1
    template:
      retry:
        enabled: false
        max-attempts: 1
  cloud:
    stream:
      bindings:
        output:
          # group: ts-return-cancel
          destination: rest-service-collect-exchange
          contentType: text/plain
          binder: rabbit
        input:
          group: rest-service-collect
          destination: rest-service-collect-exchange
          contentType: text/plain
          binder: rabbit

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9413